// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFmgTLHxJRPmuXkubtqaxryb-qffYOao',
    appId: '1:247784966868:web:c5be58411aa92f09084941',
    messagingSenderId: '247784966868',
    projectId: 'kumpaskonek',
    authDomain: 'kumpaskonek.firebaseapp.com',
    storageBucket: 'kumpaskonek.firebasestorage.app',
    measurementId: 'G-TD7X4ZWCN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5NEvkWYJAFp5IJ-ePZrMTseZiy8ZhCI',
    appId: '1:247784966868:android:1667b4352f139933084941',
    messagingSenderId: '247784966868',
    projectId: 'kumpaskonek',
    storageBucket: 'kumpaskonek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8bYg1LG6ywI0_Q3LEO2YiP2Ut7u9OY0',
    appId: '1:247784966868:ios:204ce19a444b5c0c084941',
    messagingSenderId: '247784966868',
    projectId: 'kumpaskonek',
    storageBucket: 'kumpaskonek.firebasestorage.app',
    iosBundleId: 'com.example.kumpaskonek12',
  );
}
